[package]
name = "rust-eop"
version = "0.1.0"
authors = ["Kristoffer Andersson <kode.kristoff@gmail.com>"]

[lib]
name = "eop"
path = "src/lib.rs"

[[bin]]
name = "eop-tests"
path = "src/main.rs"

[dependencies]
