[package]
name = "fm2gp"
version = "0.1.0"
authors = ["Kristoffer Andersson <kode.kristoff@gmail.com>"]

[lib]
name = "fm2gp"
path = "src/lib.rs"

[[bin]]
name = "fm2gp-tests"
path = "src/main.rs"

[dependencies]
